spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    #  local host
    #url: jdbc:mysql://localhost:3306/BASIL_ODS_PRD?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT-4&allowMutiQueries=true&zeroDateTimeBehavior=convertToNull
    #username: root
    #password: pax@4901

    #  AWS UAT
    url: jdbc:mysql://basilmysql1.c3156zibo6aq.us-east-1.rds.amazonaws.com:3306/BASIL_ODS_PRD?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT-4&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: BASIL_ODS_PRD
    password: PaxUser@123

    #  AWS PROD
#    url: jdbc:mysql://prodbasilmysql.c09xunhasest.us-east-1.rds.amazonaws.com:3306/BASIL_ODS_PRD?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT-5&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: BASIL_ODS_PRD
#    password: PaxUser@123

security:
  # urls which do not need authentication
  permit-all:
    urls:
      - /webjars/**
      - /swagger-resources
      - /swagger-ui.html
      - /swagger-resources/**
      - /v2/**
      - /internal/**
      - /error
      - /api/**
      - /password/**

  # CORS configuration
  cors:
    configs:
      - path: "/**"
        #        origins: 'http://localhost:8080'
        #       origins: 'http://216.238.144.197:8888/'
        origins: "*"
        headers: "*"
        methods: "*"
        allowCredentials: true
        maxAge: 3600

#  configuration:
#    map-underscore-to-camel-case: false

#logging:
#  config: logback-spring.xml
#  level:
#    org.springframework.security: debug

server:
  servlet:
    context-path: /api/v1/
    session:
      timeout: 3600
  port: 8081
  tomcat:
    remote_ip_header: X-Forwarded-For
    protocol_header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
    basedir: ./
    accesslog:
      enabled: true
      directory: service-logs
  ssl:
    enabled: false
    key-store: server.keystore
    key-store-password: pax@4901FL!2
    key-store-type: JKS
    #trust-store: src/test/resources/trust.keystore
    #trust-store-password: pax@4901
    #trust-store-type: JKS
    #trust-store-provider: SUN
    #client-auth: need
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
  
frontend:  
  urls:
    activate: http://localhost:9000/activate-user/
    change: http://localhost:9000/activate-user/
    forgot: http://localhost:9000/activate-user/
    reset: http://localhost:9000/activate-user/

aws:
  enabled: true
  local_development: true
  region: us-east-1
  accessKeyId: ASIA6DUFT7CDOAZBEB2T
  secretKey: LbKB1hUtwWNeuNYzsE1JksBX6qxnMND2yVMfy1Kd
  sessionToken: IQoJb3JpZ2luX2VjEDYaCXVzLWVhc3QtMiJGMEQCICFUjBNGVlM6ADxaZHxlgPtgBRXIPDNJTrKanPNa3CdtAiAsimLWcZf1ugqctj40pDTXTe9LYY4fXNCI7Qw8RTio0CqCAwjP//////////8BEAEaDDk2OTg2OTA5NzA5NCIMknkL078NqWNz7zXSKtYCeYXDK5WEhA8cIEHKwS49qTRRJzwLfwuC0LnH/IPcUUsKzORRZ8TFBVEMeXTr3Um9Y3FIhJvxSXpwrjnbgQl0Q0qL3ZbkooEAPcG79q8WDk7+RjREoNeadW+CTvhO7ej36BX0Ymfu4A03Kd6Tr3hkRdmoSjtAMcrpK6bSfMg63AXdVVdNoxy1Bw5ObbW1Wz1/GA0HP6jKN+wjfAIwYoQy4zRXwgiKOB6fgyOTFuMtXyNl7558B7VACIpbPQrBMelv2pLhcsL1/+ZCsVzJJSHNWyhW2BoCBzJZJk8QeQ+tFMQkfIHcDVju5l/8euwdEuBDe6x8Ftd0Bu7XP7HMQzhPGD0MeHwtmWkOTCGR0umKGzgOboS/rGlYpuwWXdxSlre1MbLnSliVCB1N3VMAGL1HyHHKoCTmbPa60G27H5ebYjeSqusKC3JC+LTwjw13D9SnaEoqvJ9VMO2o7qwGOqgBtp0rBp0CczMVz38KLdxoUjscTqW2J7vgviq5QRE0s80vDNmXeV5OwbVrgUtWyelZGm9I4neAjRBvNyLXlbOg+ZV3brHQZUhCoiuJQXFb+kGLIwrpJcvYbKBexXjD2fgE0BrK0+DnDF/Zv/gDL7AdFwel9o/YEMBV59Q84PYW8uTl34XYD3SqQSxjOSA2rlgumYIcM9VCuOs9KJ+s9ssUnDm3IVBknPDR
  threads:
    min: 10
    max: 30
    queueLimit: 200
