spring:
  application:
    name: basil
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  datasource:
    #  AWS
    url: jdbc:mysql://prodbasilmysql.c09xunhasest.us-east-1.rds.amazonaws.com:3306/BASIL_ODS_PRD?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT-5&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${BASIL_PROD_DB_USERNAME}
    password: ${BASIL_PROD_DB_PASSWORD}

  mail:
    host: smtp.office365.com
    port: 587
    protocol: smtp
    username: ${BASIL_PROD_SMTP_USERNAME}
    password: ${BASIL_PROD_SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000

security:
  # urls which do not need authentication
  permit-all:
    urls:
      - /webjars/**
      - /swagger-resources
      - /swagger-ui.html
      - /swagger-resources/**
      - /v2/**
      - /internal/**
      - /error
      - /api/**
      #      - /api/v1/**
      - /user/**
      - /password/**
      - /privilege/**
      - /rma/**

  # CORS configuration
  cors:
    configs:
      - path: "/**"
        #        origins: 'http://localhost:8080'
        #       origins: 'http://216.238.144.197:8888/'
        origins: "*"
        headers: "*"
        methods: "*"
        allowCredentials: true
        maxAge: 3600

#  configuration:
#    map-underscore-to-camel-case: false

logging:
  config: conf/logback-spring.xml
  level:
    org.springframework.security: debug

server:
  servlet:
    context-path: /api/v1/
    session:
      timeout: 3600
  port: 8989
  tomcat:
    remote_ip_header: X-Forwarded-For
    protocol_header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
    basedir: ./
    accesslog:
      enabled: true
      directory: service-logs
  ssl:
    enabled: false
    key-store: server.keystore
    key-store-password: ${BASIL_PROD_SSL_KEY_STORE_PASSWORD}
    key-store-type: JKS
    #trust-store: src/test/resources/trust.keystore
    #trust-store-password: ${BASIL_PROD_SSL_TRUST_STORE_PASSWORD}
    #trust-store-type: JKS
    #trust-store-provider: SUN
    #client-auth: need
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

frontend:
  urls:
    activate: https://basilclient.paxcenters.com/activate-user/
    change: https://basilclient.paxcenters.com/activate-user/
    forgot: https://basilclient.paxcenters.com/activate-user/
    reset: https://basilclient.paxcenters.com/activate-user/

aws:
  enabled: true
  local_development: true
  region: us-east-1
  accessKeyId: ${BASIL_PROD_AWS_ACCESS_KEY_ID}
  secretKey: ${BASIL_PROD_AWS_SECRET_KEY}
  sessionToken: ${BASIL_PROD_AWS_SESSION_TOKEN}

rma:
  file-storage:
    bucket: basil-uat-cp-file-storage
    use-s3: true
    base-prefix: tickets
    local-root: ./basil-uat-cp-file-storage
    presign-expire-minutes: 30

mail:
  smtp:
    enabled: false

contact-rma:
  mail:
    to: RMAsupport@pax.us

